using UnityEditor;
using UnityEngine;
using System;
using System.IO;
using System.Text;
using System.Linq;

namespace UVS.Editor.Core
{
    public static class CodeGeneratorSettings
    {
        public const string OutputFolderPrefKey = "UVS.CodeGen.OutputFolder";
        public const string AutoSyncPrefKey = "UVS.CodeGen.AutoSync";

        public static string OutputFolder
        {
            get => EditorPrefs.GetString(OutputFolderPrefKey, "Assets/UVSGenerated");
            set => EditorPrefs.SetString(OutputFolderPrefKey, value);
        }

        public static bool AutoSync
        {
            get => EditorPrefs.GetBool(AutoSyncPrefKey, true);
            set => EditorPrefs.SetBool(AutoSyncPrefKey, value);
        }
    }

    public static class VehicleRuntimeCodeGenerator
    {
        public const string GeneratedNamespace = "UVS.Generated";

        public static string GetRuntimeClassName(VehicleConfig config)
        {
            string raw = !string.IsNullOrEmpty(config.id) ? config.id : config.name;
            string safe = SanitizeClassName(raw);
            string suffix = !string.IsNullOrEmpty(config.prefabGuid) ? config.prefabGuid[..8] : Math.Abs(config.GetInstanceID()).ToString();
            return $"UVSRuntime_{safe}_{suffix}";
        }

        public static string GetRuntimeScriptPath(VehicleConfig config)
        {
            string folder = NormalizeOutputFolder(CodeGeneratorSettings.OutputFolder);
            return $"{folder}/{GetRuntimeClassName(config)}.cs";
        }

        public static void GenerateRuntimeScript(VehicleConfig config)
        {
            if (config == null) return;

            string folder = NormalizeOutputFolder(CodeGeneratorSettings.OutputFolder);
            EnsureFolderExists(folder);

            string className = GetRuntimeClassName(config);
            string scriptPath = GetRuntimeScriptPath(config);

            var sb = new StringBuilder();
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("");
            sb.AppendLine($"namespace {GeneratedNamespace}");
            sb.AppendLine("{");
            sb.AppendLine($"    // Auto-generated by UVS Code Generator on {DateTime.Now:yyyy-MM-dd}");
            sb.AppendLine($"    public class {className} : MonoBehaviour");
            sb.AppendLine("    {");
            sb.AppendLine("        public VehicleConfig config;");
            sb.AppendLine($"        public string VehicleId => \"{Escape(config.id)}\";");
            sb.AppendLine($"        public string VehicleName => \"{Escape(config.vehicleName)}\";");
            sb.AppendLine($"        public VehicleConfig.VehicleType VehicleType => VehicleConfig.VehicleType.{config.vehicleType};");
            sb.AppendLine($"        public string Category => \"{Escape(config.GetCurrentCategory())}\";");
            sb.AppendLine($"        public string Specialized => \"{Escape(config.GetCurrentSpecialized())}\";");
            sb.AppendLine("");
            sb.AppendLine("        private void Awake()");
            sb.AppendLine("        {");
            sb.AppendLine("            if (config == null) return;");
            sb.AppendLine("        }");
            sb.AppendLine("");
            sb.AppendLine("        public void ApplyBodySettings()");
            sb.AppendLine("        {");
            sb.AppendLine("            if (config == null) return;");
            sb.AppendLine("            if (TryGetComponent<Rigidbody>(out var rb))");
            sb.AppendLine("            {");
            sb.AppendLine("                rb.mass = config.body.mass;");
            sb.AppendLine("                rb.centerOfMass = config.body.centerOfMassOffset;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(scriptPath, sb.ToString());
            AssetDatabase.ImportAsset(scriptPath);
        }

        public static void GenerateAll()
        {
            var guids = AssetDatabase.FindAssets("t:VehicleConfig");
            foreach (var guid in guids)
            {
                var path = AssetDatabase.GUIDToAssetPath(guid);
                var cfg = AssetDatabase.LoadAssetAtPath<VehicleConfig>(path);
                if (cfg != null)
                    GenerateRuntimeScript(cfg);
            }
        }

        public static Type GetGeneratedType(VehicleConfig config)
        {
            if (config == null) return null;
            string className = GetRuntimeClassName(config);
            string fullName = $"{GeneratedNamespace}.{className}";

            var type = Type.GetType($"{fullName}, Assembly-CSharp");
            if (type != null) return type;

            var scriptPath = GetRuntimeScriptPath(config);
            var script = AssetDatabase.LoadAssetAtPath<MonoScript>(scriptPath);
            return script != null ? script.GetClass() : null;
        }

        private static void EnsureFolderExists(string folder)
        {
            if (AssetDatabase.IsValidFolder(folder)) return;

            string[] parts = folder.Split('/');
            string current = parts[0];
            for (int i = 1; i < parts.Length; i++)
            {
                string next = $"{current}/{parts[i]}";
                if (!AssetDatabase.IsValidFolder(next))
                    AssetDatabase.CreateFolder(current, parts[i]);
                current = next;
            }
        }

        private static string NormalizeOutputFolder(string folder)
        {
            if (string.IsNullOrWhiteSpace(folder))
                return "Assets/UVSGenerated";

            if (!folder.Replace("\\", "/").StartsWith("Assets"))
                return "Assets/UVSGenerated";

            return folder.Replace("\\", "/").TrimEnd('/');
        }

        private static string SanitizeClassName(string raw)
        {
            if (string.IsNullOrEmpty(raw))
                return "Vehicle";

            var sb = new StringBuilder();
            foreach (char c in raw)
            {
                if (char.IsLetterOrDigit(c) || c == '_')
                    sb.Append(c);
            }

            if (sb.Length == 0)
                sb.Append("Vehicle");

            if (!char.IsLetter(sb[0]) && sb[0] != '_')
                sb.Insert(0, 'V');

            return sb.ToString();
        }

        private static string Escape(string value)
        {
            if (string.IsNullOrEmpty(value)) return string.Empty;
            return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
        }
    }
}
